markdown: redcarpet
pygments: true
permalink: /:categories/:title/

redcarpet: 
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

url:
  http://cole-trapnell-lab.github.io

#analytics: 'UA-58618307-1'

pagination: true
paginate: 5

exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.xml"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"
